-- Complete the class directory using the 47 active classes published by
-- Spacio BLNC before the Veora rebrand. The 14 Classics and 5 Ballet class
-- types were seeded in 0001; this adds the 28 Restore formats so staff can
-- schedule them and customers can see/book the exact class name.

set statement_timeout = '30s';

insert into public.class_types
  (slug, name, category, service_slug, duration_minutes, level, description)
values
  ('heated-barre', 'Heated Barre', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve posture, balance and muscle endurance with low-impact movement in a warm, energizing environment.'),
  ('heated-functional-group-exercise', 'Heated Functional Group Exercise', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve strength, mobility and endurance in infrared heat that supports circulation and recovery.'),
  ('heated-hiit', 'Heated HIIT', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Boost cardiovascular fitness, burn calories and improve endurance with high-intensity intervals in infrared heat.'),
  ('heated-mat-pilates', 'Heated Mat Pilates', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Strengthen your core, improve flexibility and enhance mobility in soothing infrared heat.'),
  ('heated-mat-sculpt', 'Heated Mat Sculpt', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Build lean muscle, improve endurance and tone your body with the added benefits of infrared heat.'),
  ('heated-mat-strength', 'Heated Mat Strength', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Develop functional strength, stability and balance while infrared heat warms muscles and supports flexibility.'),
  ('heated-ashtanga', 'Heated Ashtanga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Develop strength, endurance and discipline while infrared heat supports flexibility and muscle recovery.'),
  ('heated-gentle-flow-yoga', 'Heated Gentle Flow Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve mobility, balance and relaxation through slow, mindful movement in a comfortably heated space.'),
  ('heated-hatha', 'Heated Hatha', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve flexibility, balance and relaxation with traditional yoga practiced in soothing infrared heat.'),
  ('heated-power-yoga', 'Heated Power Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Build strength, stamina and confidence through dynamic yoga in an invigorating heated studio.'),
  ('heated-restorative-yoga', 'Heated Restorative Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Reduce stress, improve flexibility and promote deep relaxation with gentle poses enhanced by infrared warmth.'),
  ('heated-stretch-yoga', 'Heated Stretch Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve flexibility, mobility and recovery while infrared heat helps release muscle tension.'),
  ('heated-vinyasa-yoga', 'Heated Vinyasa Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Build strength, flexibility and focus through flowing movement enhanced by infrared heat.'),
  ('heated-yogalates', 'Heated Yogalates', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve strength, flexibility and core stability in infrared heat that supports recovery and relaxation.'),
  ('red-light-barre', 'Red Light + Barre', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve posture, balance and muscle endurance while red light therapy supports recovery and vitality.'),
  ('red-light-functional-group-exercise', 'Red Light + Functional Group Exercise', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve strength, mobility and endurance while red light therapy supports muscle recovery and wellness.'),
  ('red-light-hiit', 'Red Light + HIIT', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Boost cardiovascular fitness, burn calories and support post-workout recovery with red light therapy.'),
  ('red-light-mat-pilates', 'Red Light + Mat Pilates', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Strengthen your core, improve flexibility and enhance recovery with red light therapy.'),
  ('red-light-mat-sculpt', 'Red Light + Mat Sculpt', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Build lean muscle, improve endurance and tone your body while red light therapy supports recovery.'),
  ('red-light-mat-strength', 'Red Light + Mat Strength', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Develop functional strength, stability and balance with red light therapy supporting performance and recovery.'),
  ('red-light-ashtanga', 'Red Light + Ashtanga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Develop strength, endurance and discipline while supporting muscle recovery with red light therapy.'),
  ('red-light-gentle-flow-yoga', 'Red Light + Gentle Flow Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve mobility, balance and relaxation while red light therapy supports recovery and well-being.'),
  ('red-light-hatha', 'Red Light + Hatha', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve flexibility, balance and relaxation while red light therapy supports overall wellness.'),
  ('red-light-power-yoga', 'Red Light + Power Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Build strength, stamina and confidence while red light therapy helps support recovery between sessions.'),
  ('red-light-restorative-yoga', 'Red Light + Restorative Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Reduce stress, improve flexibility and promote deep relaxation with the calming benefits of red light therapy.'),
  ('red-light-stretch-yoga', 'Red Light + Stretch Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve flexibility, mobility and recovery while red light therapy helps reduce muscle fatigue.'),
  ('red-light-vinyasa-yoga', 'Red Light + Vinyasa Yoga', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Build strength, flexibility and focus with flowing yoga complemented by red light therapy.'),
  ('red-light-yogalates', 'Red Light + Yogalates', 'Recovery & Restore', 'recovery-restore', 50, 'Open to all',
    'Improve strength, flexibility and core stability while red light therapy supports recovery and wellness.')
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  service_slug = excluded.service_slug,
  duration_minutes = excluded.duration_minutes,
  level = excluded.level,
  description = excluded.description,
  active = true;

update public.services
set
  short_description = 'Twenty-eight heated and red light therapy class options.',
  description = 'Our Restore collection includes heated and red light therapy versions of every Classics format, from Pilates and yoga to barre, strength and HIIT. Choose the movement you enjoy with an environment designed to support warmth, circulation and recovery.',
  class_variants = array[
    'Heated Barre',
    'Heated Functional Group Exercise',
    'Heated HIIT',
    'Heated Mat Pilates',
    'Heated Mat Sculpt',
    'Heated Mat Strength',
    'Heated Ashtanga',
    'Heated Gentle Flow Yoga',
    'Heated Hatha',
    'Heated Power Yoga',
    'Heated Restorative Yoga',
    'Heated Stretch Yoga',
    'Heated Vinyasa Yoga',
    'Heated Yogalates',
    'Red Light + Barre',
    'Red Light + Functional Group Exercise',
    'Red Light + HIIT',
    'Red Light + Mat Pilates',
    'Red Light + Mat Sculpt',
    'Red Light + Mat Strength',
    'Red Light + Ashtanga',
    'Red Light + Gentle Flow Yoga',
    'Red Light + Hatha',
    'Red Light + Power Yoga',
    'Red Light + Restorative Yoga',
    'Red Light + Stretch Yoga',
    'Red Light + Vinyasa Yoga',
    'Red Light + Yogalates'
  ]::text[]
where slug = 'recovery-restore';
