-- Complete package catalog confirmed from the August pricing sheet.
-- The prior client clarification takes precedence over the outdated names in
-- the sheet: 6 months = Signature and 12 months = Prestige at P6,000/month.
-- Discovery and Infratone are intentionally excluded from the September sale.

insert into public.packages (
  slug,
  name,
  category,
  package_group,
  service_slug,
  price_centavos,
  original_price_centavos,
  credit_count,
  validity_description,
  validity_days,
  expires_from,
  description,
  included_services,
  conditions,
  is_recommended,
  recommended_label,
  is_founder_offer,
  is_active,
  sort_order,
  entitlement_type,
  membership_duration_months,
  unlimited_booking,
  sale_starts_at,
  sale_ends_at
)
values
  (
    'founding-classic-intro',
    'Veora Discovery Pass',
    'classic',
    'intro_offer',
    null,
    99900,
    null,
    1,
    '5 days from purchase',
    5,
    'purchase',
    'Your introductory Veora class at the existing Discovery Pass rate.',
    array['1 class credit', 'Valid for 5 days from purchase'],
    array['Intro pricing is not part of the September 10% promotion'],
    true,
    'First visit',
    false,
    true,
    1,
    'credits',
    null,
    false,
    null,
    null
  ),
  (
    '3-class-package',
    'Veora Essence',
    'classic',
    'package',
    null,
    270000,
    300000,
    3,
    '3 classes',
    null,
    'purchase',
    'Three flexible Veora class credits.',
    array['3 class credits'],
    array['September promo price: ₱2,700', 'Non-transferable'],
    false,
    null,
    true,
    true,
    20,
    'credits',
    null,
    false,
    '2026-09-01 00:00:00+08'::timestamptz,
    '2026-10-01 00:00:00+08'::timestamptz
  ),
  (
    '6-class-package',
    'Veora Flow',
    'classic',
    'package',
    null,
    486000,
    540000,
    6,
    '6 classes',
    null,
    'purchase',
    'Six flexible Veora class credits.',
    array['6 class credits'],
    array['September promo price: ₱4,860', 'Non-transferable'],
    false,
    null,
    true,
    true,
    21,
    'credits',
    null,
    false,
    '2026-09-01 00:00:00+08'::timestamptz,
    '2026-10-01 00:00:00+08'::timestamptz
  ),
  (
    'veora-unlimited',
    'Veora Unlimited',
    'classic',
    'membership',
    null,
    810000,
    900000,
    null,
    '1 month',
    null,
    'purchase',
    'A one-month Veora membership for a consistent daily practice.',
    array['Maximum 1 class per day', '1-month membership term'],
    array['September promo price: ₱8,100', 'Non-transferable'],
    false,
    null,
    true,
    true,
    29,
    'unlimited',
    1,
    true,
    '2026-09-01 00:00:00+08'::timestamptz,
    '2026-10-01 00:00:00+08'::timestamptz
  ),
  (
    '6-month-unlimited',
    'Veora Signature',
    'classic',
    'membership',
    null,
    720000,
    800000,
    null,
    '6-month contract',
    null,
    'purchase',
    'A six-month Classics membership with one class available each day.',
    array['Maximum 1 class per day', 'Monthly auto-payment', '6-month membership term'],
    array['September promo price: ₱7,200/month', 'Non-transferable'],
    true,
    'September offer',
    true,
    false,
    30,
    'unlimited',
    6,
    true,
    '2026-09-01 00:00:00+08'::timestamptz,
    '2026-10-01 00:00:00+08'::timestamptz
  ),
  (
    '12-month-unlimited',
    'Veora Prestige',
    'classic',
    'membership',
    null,
    540000,
    600000,
    null,
    '12-month contract',
    null,
    'purchase',
    'A twelve-month Classics membership with one class available each day.',
    array['Maximum 1 class per day', 'Monthly auto-payment', '12-month membership term'],
    array['September promo price: ₱5,400/month', 'Non-transferable'],
    false,
    null,
    true,
    false,
    31,
    'unlimited',
    12,
    true,
    '2026-09-01 00:00:00+08'::timestamptz,
    '2026-10-01 00:00:00+08'::timestamptz
  ),
  (
    'infratone-intro-class',
    'Infratone Intro Class',
    'restore',
    'single_session',
    'recovery-restore',
    139900,
    null,
    1,
    'Intro session',
    null,
    'purchase',
    'An introductory Infratone session for first-time clients.',
    array['1 Infratone session'],
    array['Not included in the September 10% promotion'],
    false,
    null,
    false,
    true,
    40,
    'credits',
    null,
    false,
    null,
    null
  ),
  (
    'infratone-unlimited',
    'Infratone Unlimited',
    'restore',
    'membership',
    'recovery-restore',
    1549900,
    null,
    null,
    'Unlimited Infratone',
    null,
    'purchase',
    'Unlimited access to eligible Infratone sessions during the membership term.',
    array['Unlimited eligible Infratone sessions'],
    array['Not included in the September 10% promotion', 'Non-transferable'],
    false,
    null,
    false,
    false,
    41,
    'unlimited',
    1,
    true,
    null,
    null
  )
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  package_group = excluded.package_group,
  service_slug = excluded.service_slug,
  price_centavos = excluded.price_centavos,
  original_price_centavos = excluded.original_price_centavos,
  credit_count = excluded.credit_count,
  validity_description = excluded.validity_description,
  validity_days = excluded.validity_days,
  expires_from = excluded.expires_from,
  description = excluded.description,
  included_services = excluded.included_services,
  conditions = excluded.conditions,
  is_recommended = excluded.is_recommended,
  recommended_label = excluded.recommended_label,
  is_founder_offer = excluded.is_founder_offer,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  entitlement_type = excluded.entitlement_type,
  membership_duration_months = excluded.membership_duration_months,
  unlimited_booking = excluded.unlimited_booking,
  sale_starts_at = excluded.sale_starts_at,
  sale_ends_at = excluded.sale_ends_at,
  updated_at = now();
