"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { Check, KeyRound } from "lucide-react";
import {
  startTotpEnrollmentAction,
  refreshTotpChallengeAction,
  verifyTotpEnrollmentAction,
} from "@/lib/auth/totp-mfa-actions";
import { Button } from "@/components/ui/Button";
import { OtpInput } from "@/components/auth/OtpInput";

type Step = "start" | "scan" | "success";

export function TotpEnrollFlow({ redirectTo }: { redirectTo: string }) {
  const router = useRouter();
  const [step, setStep] = useState<Step>("start");
  const [factorId, setFactorId] = useState<string | null>(null);
  const [challengeId, setChallengeId] = useState<string | null>(null);
  const [qrCode, setQrCode] = useState<string | null>(null);
  const [secret, setSecret] = useState<string | null>(null);
  const [code, setCode] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleStart() {
    setSubmitting(true);
    setError(null);
    try {
      const result = await startTotpEnrollmentAction();
      if ("error" in result) {
        setError(result.error);
        return;
      }
      if ("alreadyEnrolled" in result) {
        setStep("success");
        return;
      }
      setFactorId(result.factorId);
      setChallengeId(result.challengeId);
      setQrCode(result.qrCode);
      setSecret(result.secret);
      setStep("scan");
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setSubmitting(false);
    }
  }

  async function handleVerify(event: React.FormEvent) {
    event.preventDefault();
    if (!factorId) return;
    setSubmitting(true);
    setError(null);
    try {
      let activeChallengeId = challengeId;
      const result = activeChallengeId
        ? await verifyTotpEnrollmentAction(factorId, activeChallengeId, code)
        : { error: "Something went wrong. Please try again." };

      if ("error" in result) {
        // The challenge may have expired if the user took a while — open a
        // fresh one automatically rather than making them start over.
        const refreshed = await refreshTotpChallengeAction(factorId);
        if ("challengeId" in refreshed) {
          activeChallengeId = refreshed.challengeId;
          setChallengeId(refreshed.challengeId);
        }
        setError(result.error);
        setCode("");
        return;
      }

      setStep("success");
      setTimeout(() => {
        router.push(redirectTo);
        router.refresh();
      }, 1200);
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <AnimatePresence mode="wait">
      {step === "success" ? (
        <motion.div
          key="success"
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col items-center rounded-2xl border border-charcoal/10 bg-cream/40 px-8 py-16 text-center"
        >
          <span className="flex h-12 w-12 items-center justify-center rounded-full bg-charcoal text-ivory">
            <Check size={22} />
          </span>
          <p className="font-display mt-6 text-2xl text-charcoal">Authenticator app connected.</p>
          <p className="mt-2 max-w-sm text-charcoal/65">Taking you back now…</p>
        </motion.div>
      ) : step === "scan" ? (
        <motion.form key="scan" initial={{ opacity: 0 }} animate={{ opacity: 1 }} onSubmit={handleVerify} className="flex flex-col items-center">
          <span className="flex h-12 w-12 items-center justify-center rounded-full bg-cream text-clay">
            <KeyRound size={20} aria-hidden />
          </span>
          <p className="font-display mt-6 text-2xl text-charcoal">Scan with your authenticator app</p>
          <p className="mt-2 max-w-sm text-center text-charcoal/65">
            Use Google Authenticator, 1Password or a similar app to scan this code, then enter the 6-digit code
            it generates.
          </p>

          {qrCode && (
            // The QR code is a per-enrollment SVG data URI generated by
            // Supabase — not an optimizable static asset, so next/image
            // doesn't apply here.
            // eslint-disable-next-line @next/next/no-img-element
            <img src={qrCode} alt="Scan this QR code with your authenticator app" className="mt-6 h-44 w-44 rounded-xl border border-charcoal/10 bg-ivory p-2" />
          )}

          {secret && (
            <p className="mt-3 max-w-sm break-all text-center text-xs text-charcoal/45">
              Can&rsquo;t scan? Enter this key manually: <span className="text-charcoal/70">{secret}</span>
            </p>
          )}

          <div className="mt-8">
            <OtpInput value={code} onChange={setCode} disabled={submitting} autoFocus />
          </div>

          {error && <p className="mt-4 text-sm text-red-600">{error}</p>}

          <Button type="submit" size="lg" disabled={submitting || code.length !== 6} className="mt-8 w-full max-w-xs">
            {submitting ? "Verifying…" : "Verify & Enable"}
          </Button>
        </motion.form>
      ) : (
        <motion.div key="start" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-col items-center text-center">
          <span className="flex h-12 w-12 items-center justify-center rounded-full bg-cream text-clay">
            <KeyRound size={20} aria-hidden />
          </span>
          <p className="font-display mt-6 text-2xl text-charcoal">Set up an authenticator app</p>
          <p className="mt-2 max-w-sm text-charcoal/65">
            Add a second sign-in step using an authenticator app on your phone — no SMS required, works
            immediately.
          </p>
          {error && <p className="mt-4 text-sm text-red-600">{error}</p>}
          <Button type="button" size="lg" onClick={handleStart} disabled={submitting} className="mt-8 w-full max-w-xs">
            {submitting ? "Starting…" : "Get Started"}
          </Button>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
